name: Generate Pacman Contribution Graph

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=4096"
    steps:
      - uses: actions/checkout@v3
      - name: Run Pacman Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: satriabumi
          github_token: ${{ secrets.GITHUB_TOKEN }}
